### ISSUE TITLE
Crash when closing shared window

### ISSUE THREAD

**Issue by RFCOSOCIETY** [DolbyIO/comms-sdk-unreal#416] opened 2023-09-21 11:01 UTC
**Describe the bug**

The application crashes whenever a shared window is closed.
![image](https://github.com/DolbyIO/comms-sdk-unreal/assets/127212080/5c1d6d34-81a6-466c-b9dc-d67602d3c052)

**Expected Behavior**

To not crash.

**Minimalistic code (recommended)**

No code needed as the crash happens here:
![image](https://github.com/DolbyIO/comms-sdk-unreal/assets/127212080/c84190a3-d402-4db4-a2ba-8bc275fb2068)

**Specifications**

-  Windows 11 22H2
-   Version:
    -   comms-sdk-unreal 1.2.0

**Comment by djova-dolby** [comment] 2023-10-05 14:59
If it does not work can you set a break point the Handle(const screen_share_error&) function and provide the stack values of in error structure?

**Comment by djova-dolby** [comment] 2023-10-06 15:10
Ok I can confirm this issue is fixed here: https://github.com/DolbyIO/comms-sdk-unreal/pull/419 so the latest artifacts in [github actions artifacts](https://github.com/DolbyIO/comms-sdk-unreal/actions/runs/6429932172) have the fix. If running on macOS you will need to unquarantine the binaries since it is not official release.
The problem was that Unreal was trying to log an enum class as string which would just crash.

**Comment by djova-dolby** [comment] 2023-10-09 13:36
Fixed in latest main. Release coming soon

**Closed by djova-dolby** 2023-10-09 13:36 UTC
Labels: bug
