### ISSUE TITLE
Unresolved RHI external symbols

### ISSUE THREAD

**Issue by GaryMakinDolby** [DolbyIO/comms-sdk-unreal#322] opened 2023-07-21 07:43 UTC
Copied from bug report elsewhere:

> I am trying to compile the 1.1.1 version of the plugin in our project, but it doesent compile. It seems like it's a linking problem. When io press compile the DolbyIO.dll disapears from the DolbyIO\Binaries\Win64 folder

> I am also seeing the 1.1.2 version published just now, but same thing happens. I am also trying in a secondary PC that has windows 11, Intel architecture and UE5.2 Source version, instead of launcher. And its compiling there

![image](https://github.com/DolbyIO/comms-sdk-unreal/assets/63078160/276cd74f-9217-4caf-abf0-9851c10b26a5)
![image](https://github.com/DolbyIO/comms-sdk-unreal/assets/63078160/e2d05516-dcad-4ad6-af08-b42480165006)

**Comment by kubaau** [comment] 2023-07-21 07:54
@ivananfruns could you describe the reproduction steps in more detail?

- If Windows 11 + UE 5.2 from source work, what platform does not?
- How is the project set up? Are you using the plugin from C++ or just through Blueprints?
- What are the exact steps to reproduce this issue? Is is possible to reproduce it with a new project?
- Did this issue exist in release 1.1.0 or some 1.1.0-beta?

**Comment by kubaau** [comment] 2023-07-21 08:08
There is a way for me to reproduce a similar issue albeit with a wrong plugin build script:

![image](https://github.com/DolbyIO/comms-sdk-unreal/assets/18394363/d7422d38-bf7c-406e-96d8-59f50fe8920a)

This happens when [Build.cs](https://github.com/DolbyIO/comms-sdk-unreal/blob/main/DolbyIO/Source/DolbyIO.Build.cs) does not contains "RHI" in PublicDependencyModuleNames. Perhaps this entry is missing from somewhere in the project which reproduces the issue?

**Comment by ivananfruns** [comment] 2023-07-24 08:50
> @ivananfruns could you describe the reproduction steps in more detail?
> 
> * If Windows + UE 5.2 from source work, what combination does not? Which Visual Studio (exactly) works and which doesn't?
> * Are you using the plugin from C++ or just through Blueprints?
> * What are the exact steps to reproduce this issue? Is is possible to reproduce it with a new project?
> * Did this issue exist in release 1.1.0 or some 1.1.0-beta?

I am using the binary UE5.2, with Visual studio 2022. We have a C++  and Blueprints project, even though the implementation for Dolby is on BPs. 

This issue didnt exist in release 1.1.0 or any other before. We have been using the plugin for 4 months now. 
In our case we are just substituting the DolbyIO folder and trying to compile the project. We haven't been able to reproduce it on a blank project, so this would suggest there is something wrong with our project, although putting back the 1.1.0 version compiles just well.

**Comment by ivananfruns** [comment] 2023-07-24 08:53
> There is a way for me to reproduce a similar issue albeit with a wrong plugin build script:
> 
> ![image](https://user-images.githubusercontent.com/18394363/255112850-d7422d38-bf7c-406e-96d8-59f50fe8920a.png)
> 
> This happens when [Build.cs](https://github.com/DolbyIO/comms-sdk-unreal/blob/main/DolbyIO/Source/DolbyIO.Build.cs) does not contains "RHI" in PublicDependencyModuleNames. Perhaps this entry is missing from somewhere in the project which reproduces the issue?

![image](https://github.com/DolbyIO/comms-sdk-unreal/assets/25611159/02b17f5c-09db-4201-a8d5-c36397a983b4)

This is our build.cs, i dont know if anything is missing. 

When trying to compile now this error appears. It's pretty similar, so I guess its related to the same thing.
![image](https://github.com/DolbyIO/comms-sdk-unreal/assets/25611159/33aae49d-e34c-4776-a82e-43def4fea89e)

**Comment by ivananfruns** [comment] 2023-07-24 09:06
For some reason changing the location of the project worked and now its compiling. Sometimes crazy things happens with paths I guess... 
For now you can close the incidence, thanks!

**Comment by kubaau** [comment] 2023-07-24 09:25
I have reproduced this issue by doing the following:
- create blank project
- add release 1.1.0 to Plugins
- compile
- replace release 1.1.0 with 1.1.1
- compile

This is because Unreal Build Tool does not notice the changes to `DolbyIO.Build.cs` when it's done this way. A similar but different error would happen if you switched from 1.1.1 back to 1.1.0. The solution for this is to make a change to `DolbyIO.Build.cs` (like add a space and delete it) so that when you build again something this happens: `Invalidating makefile for Issue322Editor (DolbyIO.Build.cs modified)`.

I'm guessing changing the project location also invalidated `DolbyIO.Build.cs`, but it's easier to do the above workaround. I hope we won't be needing to change `DolbyIO.Build.cs` in patch releases like 1.1.1 in the future, but if we do, this is the workaround.

@ivananfruns Please use 1.1.1 for now, I've just discovered an issue with 1.1.2 in that it is built from the wrong commit. I'll ping you here when we fix it.

**Comment by kubaau** [comment] 2023-07-24 13:07
@ivananfruns Release 1.1.2 is now fixed.

**Closed by kubaau** 2023-07-24 13:07 UTC
Labels: wontfix
